### ISSUE TITLE
(Spike!) Create an application installer

### ISSUE THREAD

**Issue by ajm5774** [EJDinki/messe#40]

**Comment by ajm5774** [comment]
Im going to be looking into this as well

**Comment by ajm5774** [comment]
I think that the best thing to do would be manually set up the laptop and tablets. Then just deploy to the laptop. We may even be able to push updates remotely.  We can give them our equipment and then they can give their equipment back to lockheed martin.  We cant make an installer for the tablets anyway, but i guess we can  write a lengthy readme for installation.

**Comment by EJDinki** [comment]
I think we still need to be able to handle allowing the software to be reinstalled. The simplest case is the laptop crashing or physically breaking.

Perhaps a compromise would be to have detailed instructions of how we set the laptop up that could be used by lockeed martin or another technical person to reset it up. It would help if we had some sort of formal write up as to why an installer couldn't be provided,  or at least a conversation about it, since we did originally say we were going to do that. We'd also have to get lockeed martin folks to agree.

And for the tablets, I agree we should just have a readme of one suggested way to put them into kiosk mode.

**Comment by ajm5774** [comment]
We can still give them install instructions, but the instructions will be complicated. Then they would just send us an email to redeploy. Im still gonna look into this more though and possibly ask for advice from some people i know.

**Comment by jonshippling** [comment]
http://www.jrsoftware.org/isinfo.php

**Comment by jonshippling** [comment]
http://installforge.net/
