### ISSUE TITLE
Maximum request length exceeded exception - limit the size of items uploaded

### ISSUE THREAD

**Issue by ajm5774** [EJDinki/messe#84]
All images were being wiped out by large files. Not sure why. Try moving stuff to the app_data folder? Google to see if its a common issue, and where image files should be stored.

**Comment by rjv9645** [comment]
Well that's fine. The mp3 files are not meant to be large.

**Comment by ajm5774** [comment]
Ideally, we would check that and handle it better instead of showing an
error page

**Comment by rjv9645** [comment]
Was actually due to something completely different. Uploading large files causes maximumrequestlength exceeded exception as expected. A google chrome extension Jonathon had installed was clicking all of the delete links on the page. We found this out because it didn't do it when he ran in incognito mode.

**Comment by rjv9645** [comment]
And to comment on AJ's "catch the error", this specific error is difficult to catch gracefully. We don't have the time. See 
http://stackoverflow.com/questions/665453/catching-maximum-request-length-exceeded
