### ISSUE TITLE
Refresh Button Url Issue

### ISSUE THREAD

**Issue by rjv9645** [EJDinki/messe#87]
Switching selections in the list and quickly hitting the edit button on the exhibits page causes

**Comment by ajm5774** [comment]
The problem was that i was using the event.target to get the href from the clicked button, but the target was actually the span within the button. I changed it to current.target and now it should be fine

**Comment by rjv9645** [comment]
But that doesn't make sense because the href was changing correctly most of the time.

**Comment by ajm5774** [comment]
It gets the href from the target. It depended which part you clicked on. If you clicked on the span in the button then the target would be the span, otherwise it would be the button itself where it actually got the href correctly. This also explains why it happened more often when using the touch screen. All i know is i debugged through the case where it generated the weird page and thats because the href it got was undefined.
